openapi: 3.0.0
info:
  description: "This is an API description for [Moira Alert API](https://moira.readthedocs.io/en/latest/overview.html). Check us out on [Github](https://github.com/moira-alert) or look up our [guide on getting started with Moira](https://moira.readthedocs.io)."
  version: "2.5.1.48"
  title: "Moira Alert"
  license:
    name: "MIT"
  contact:
    name: Moira Team
    email: opensource@skbkontur.com

tags:
  - name: "config"
    description: "View Moira's runtime configuration. For more details, see <https://moira.readthedocs.io/en/latest/installation/configuration.html/>"
  - name: "contact"
    description: "APIs for working with Moira contacts. For more details, see <https://moira.readthedocs.io/en/latest/installation/webhooks_scripts.html#contact/>"
  - name: "event"
    description: "APIs for interacting with notification events. See <https://moira.readthedocs.io/en/latest/user_guide/trigger_page.html#event-history/> for details"
  - name: "health"
    description: "interact with Moira states/health status. See <https://moira.readthedocs.io/en/latest/user_guide/selfstate.html#self-state-monitor/> for details."
  - name: "notifications"
    description: "manage notifications that are currently in queue. See <https://moira.readthedocs.io/en/latest/user_guide/hidden_pages.html#notifications/>"
  - name: "pattern"
    description: "APIs for interacting with graphite patterns in Moira. See <https://moira.readthedocs.io/en/latest/development/architecture.html#pattern/>"
  - name: "subscription"
    description: "APIs for managing a user's subscription(s). See <https://moira.readthedocs.io/en/latest/development/architecture.html#subscription/> to learn about Moira subscriptions."
  - name: "tag"
    description: "APIs for managing tags (a grouping of tags and subscriptions). See <https://moira.readthedocs.io/en/latest/user_guide/subscriptions.html#tags/>"
  - name: "trigger"
    description: "APIs for interacting with Moira triggers. See <https://moira.readthedocs.io/en/latest/development/architecture.html#trigger/> to learn about Triggers."
  - name: "team"
    description: "APIs for interacting with Moira teams."
  - name: "teamSubscription"
    description: "APIs for interacting with Moira subscriptions owned by certain team."
  - name: "teamContact"
    description: "APIs for interacting with Moira contacts owned by certain team."

servers:
  - url: http://localhost:8080/api
    description: Localhost server
paths:
  /config:
    $ref: ./config/methods.yml
  /contact:
    $ref: ./contact/methods.yml#/contacts
  /contact/{contactId}:
    $ref: ./contact/methods.yml#/contact
  /contact/{contactId}/test:
    $ref: ./contact/methods.yml#/testContact
  /event/all:
    $ref: ./event/methods.yml#/events
  /event/{triggerID}:
    $ref: ./event/methods.yml#/eventForTrigger
  /health/notifier:
    $ref: ./health/methods.yml#/notifier
  /notification:
    $ref: ./notification/methods.yml#/notifications
  /notification/all:
    $ref: ./notification/methods.yml#/all
  /pattern:
    $ref: ./pattern/methods.yml#/patterns
  /pattern/{pattern}:
    $ref: ./pattern/methods.yml#/pattern
  /subscription:
    $ref: ./subscription/methods.yml#/subscriptions
  /subscription/{subscriptionId}:
    $ref: ./subscription/methods.yml#/subscription
  /subscription/{subscriptionId}/test:
    $ref: ./subscription/methods.yml#/test
  /tag:
    $ref: ./tag/methods.yml#/tags
  /tag/{tag}:
    $ref: ./tag/methods.yml#/tag
  /tag/stats:
    $ref: ./tag/methods.yml#/stats
  /team:
    $ref: ./teams/methods.yml#/teams
  /team/{teamID}:
    $ref: ./teams/methods.yml#/team
  /team/{teamID}/users:
    $ref: ./teams/methods.yml#/teamUsers
  /team/{teamID}/users/{teamUserID}:
    $ref: ./teams/methods.yml#/teamUser
  /team/{teamID}/subscriptions:
    $ref: ./subscription/methods.yml#/teamSubscriptions
  /team/{teamID}/contacts:
    $ref: ./contact/methods.yml#/teamContacts
  /trigger:
    $ref: ./trigger/methods.yml#/triggers
  /trigger/page:
    $ref: ./trigger/methods.yml#/page
  /trigger/search:
    $ref: ./trigger/methods.yml#/search
  /trigger/{triggerID}:
    $ref: ./trigger/methods.yml#/trigger
  /trigger/{triggerID}/metrics:
    $ref: ./trigger/methods.yml#/metrics
  /trigger/{triggerID}/metrics/nodata:
    $ref: ./trigger/methods.yml#/metricsNoData
  #/trigger/{triggerID}/render:
  #  $ref: ./trigger/methods.yml#/render
  /trigger/{triggerID}/setMaintenance:
    $ref: ./trigger/methods.yml#/setMaintenance
  /trigger/{triggerID}/state:
    $ref: ./trigger/methods.yml#/state
  /trigger/{triggerID}/throttling:
    $ref: ./trigger/methods.yml#/throttling
  /user:
    $ref: ./user/methods.yml#/user
  /user/settings:
    $ref: ./user/methods.yml#/settings

components:
  schemas:
    $ref: "./shared/schemas/_index.yml"
  parameters:
    $ref: "./shared/parameters/_index.yml"
  responses:
    $ref: "./shared/responses/_index.yml"
