openapi: 3.0.0
info:
  description: "This is an API description for [Moira Alert API](https://moira.readthedocs.io/en/latest/overview.html). Check us out on [Github](https://github.com/moira-alert) or look up our [guide on getting started with Moira](https://moira.readthedocs.io)."
  version: "2.5.1.48"
  title: "Moira Alert"
  license:
    name: "MIT"
tags:
  - name: "config"
    description: "View Moira's runtime configuration. For more details, see <https://moira.readthedocs.io/en/latest/installation/configuration.html/>"
  - name: "contact"
    description: "APIs for working with Moira contacts. For more details, see <https://moira.readthedocs.io/en/latest/installation/webhooks_scripts.html#contact/>"

servers:
  - url: http://localhost:8080/api
    description: Localhost server
paths:
  /config:
    $ref: ./config/methods.yml

components:
  schemas:
    $ref: "./shared/schemas/_index.yml"
  parameters:
    $ref: "./shared/parameters/_index.yml"
  responses:
    $ref: "./shared/responses/_index.yml"