openapi: 3.0.0
info:
  description: "This is an API description for [Moira Alert API](https://moira.readthedocs.io/en/latest/overview.html). Check us out on [Github](https://github.com/moira-alert) or look up our [guide on getting started with Moira](https://moira.readthedocs.io)."
  version: "2.5.1.48"
  title: "Moira Alert"
  license:
    name: "MIT"
tags:
  - name: "config"
    description: "View Moira's runtime configuration. For more details, see <https://moira.readthedocs.io/en/latest/installation/configuration.html/>"
  - name: "contact"
    description: "APIs for working with Moira contacts. For more details, see <https://moira.readthedocs.io/en/latest/installation/webhooks_scripts.html#contact/>"
  - name: "event"
    description: "APIs for interacting with notification events. See <https://moira.readthedocs.io/en/latest/user_guide/trigger_page.html#event-history/> for details"
  - name: "health"
    description: "interact with Moira states/health status. See <https://moira.readthedocs.io/en/latest/user_guide/selfstate.html#self-state-monitor/> for details."
  - name: "notifications"
    description: "manage notifications that are currently in queue. See <https://moira.readthedocs.io/en/latest/user_guide/hidden_pages.html#notifications/>"
  - name: "pattern"
    description: "APIs for interacting with graphite patterns in Moira. See <https://moira.readthedocs.io/en/latest/development/architecture.html#pattern/>"

servers:
  - url: http://localhost:8080/api
    description: Localhost server
paths:
  /config:
    $ref: ./config/methods.yml
  /contact:
    $ref: ./contact/methods.yml#/contacts
  /contact/{contactId}:
    $ref: ./contact/methods.yml#/contact
  /contact/{contactId}/test:
    $ref: ./contact/methods.yml#/testContact
  /event/all:
    $ref: ./event/methods.yml#/events
  /event/{triggerID}:
    $ref: ./event/methods.yml#/eventForTrigger
  /health/notifier:
    $ref: ./health/methods.yml#/notifier
  /notification:
    $ref: ./notification/methods.yml#/notifications
  /notification/all:
    $ref: ./notification/methods.yml#/all
  /pattern:
    $ref: ./pattern/methods.yml#/patterns
  /pattern/{pattern}:
    $ref: ./pattern/methods.yml#/pattern

components:
  schemas:
    $ref: "./shared/schemas/_index.yml"
  parameters:
    $ref: "./shared/parameters/_index.yml"
  responses:
    $ref: "./shared/responses/_index.yml"
