trigger:
  put:
    summary: "Update existing trigger"
    operationId: UpdateTrigger
    tags:
      - trigger
    parameters:
      - $ref: parameters.yml#/triggerID
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../schemas/Trigger.yml#/Trigger"
    responses:
      $ref: responses.yml#/put
  get:
    summary: "Get an existing trigger"
    operationId: GetTrigger
    tags:
      - trigger
    parameters:
      - $ref: parameters.yml#/triggerID
    responses:
      $ref: ./responses.yml#/get
render:
  get:
    summary: "Get rendered plot for trigger"
    operationId: GetTriggerPlot
    tags:
      - trigger
    parameters:
      - $ref: parameters.yml#/triggerID
      - $ref: parameters.yml#/targetID
      - $ref: parameters.yml#/from
      - $ref: parameters.yml#/to
    responses:
      $ref: ./responses.yml#/get_render
metrics:
  get:
    summary: "Get metrics associated with certain trigger"
    operationId: GetTriggerMetrics
    tags:
      - trigger
    parameters:
      - $ref: parameters.yml#/triggerID
      - $ref: parameters.yml#/from
      - $ref: parameters.yml#/to
    responses:
      $ref: ./responses.yml#/get_metrics
