triggers:
  get:
    summary: "get all triggers"
    operationId: GetTriggers
    tags:
      - trigger
    responses:
      $ref: ./responses.yml#/triggers/getTriggers

  put:
    summary: "create new trigger"
    operationId: CreateTrigger
    tags:
      - trigger
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: ./requests.yml#/createTrigger
    responses:
      $ref: ./responses.yml#/triggers/createTrigger

trigger:
  put:
    summary: "Update existing trigger"
    operationId: UpdateTrigger
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/triggerID
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../shared/schemas/Trigger.yml#/Trigger"
    responses:
      $ref: responses.yml#/trigger/updateTrigger

  get:
    summary: "Get an existing trigger"
    operationId: GetTrigger
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/triggerID
    responses:
      $ref: ./responses.yml#/trigger/getTrigger

  delete:
    summary: "remove a trigger"
    operationId: DeleteTrigger
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/triggerID
    responses:
      $ref: ./responses.yml#/trigger/deleteTrigger

page:
  get:
    summary: "Search triggers. Deprecated, use the `search` endpoint instead"
    deprecated: true
    operationId: SearchTriggersPage
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/onlyProblems
      - $ref: ../shared/parameters/_index.yml#/page
      - $ref: ../shared/parameters/_index.yml#/text
    responses:
      $ref: ./responses.yml#/pageTriggers

search:
  get:
    summary: "Search triggers. Replaces the deprecated `page` path"
    operationId: SearchTriggers
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/onlyProblems
      - $ref: ../shared/parameters/_index.yml#/page
      - $ref: ../shared/parameters/_index.yml#/text
    responses:
      $ref: ./responses.yml#/searchTriggers

render:
  get:
    summary: "Get rendered plot for trigger"
    operationId: GetTriggerPlot
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/triggerID
      - $ref: ../shared/parameters/_index.yml#/targetID
      - $ref: ../shared/parameters/_index.yml#/from
      - $ref: ../shared/parameters/_index.yml#/to
    responses:
      $ref: ./responses.yml#/render/getTriggerChart

setMaintenance:
  put:
    summary: "sets metrics and the trigger itself to maintenance mode"
    operationId: SetTriggerMaintenance
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/triggerID
    requestBody:
      required: true
      content:
        application/json:
          schema:
            anyOf:
              - $ref: ./requests.yml#/setMaintenance/trigger
              - $ref: ./requests.yml#/setMaintenance/metrics
    responses:
      $ref: ./responses.yml#/setMaintenance/scheduleMaintenance

check:
  put:
    summary: "validates trigger target"
    operationId: CheckTrigger
    tags:
      - trigger
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../shared/schemas/Trigger.yml#/Trigger"
    responses:
      $ref: ./responses.yml#/triggers/check

metrics:
  get:
    summary: "Get metrics associated with certain trigger"
    operationId: GetTriggerMetrics
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/triggerID
      - $ref: ../shared/parameters/_index.yml#/from
      - $ref: ../shared/parameters/_index.yml#/to
    responses:
      $ref: ./responses.yml#/metrics/getMetrics
  delete:
    summary: "deletes metric from last check and all trigger pattern metrics"
    operationId: DeleteTriggerMetric
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/triggerID
      - $ref: ../shared/parameters/_index.yml#/metricName
    responses:
      $ref: ./responses.yml#/metrics/deleteMetrics

metricsNoData:
  delete:
    summary: "deletes all metrics from last data which are in NODATA state. It also deletes all trigger patterns of those metrics"
    operationId: DeleteTriggerNoDataMetrics
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/triggerID
    responses:
      $ref: ./responses.yml#/metricsNoData/delete

state:
  get:
    summary: "Get the trigger state as at last check"
    operationId: GetTriggerState
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/triggerID
    responses:
      $ref: ./responses.yml#/state/getTriggerState

throttling:
  get:
    summary: "Get a trigger with its throttling i.e its next allowed message time"
    operationId: GetTriggerThrottling
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/triggerID
    responses:
      $ref: ./responses.yml#/throttling/getThrottleInfo
  delete:
    summary: "Deletes throttling for a trigger"
    operationId: DeleteTriggerThrottling
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/triggerID
    responses:
      $ref: ./responses.yml#/throttling/deleteThrottleInfo

