triggers:
  getTriggers:
    200:
      description: "fetched all triggers"
      content:
        application/json:
          schema:
            type: object
            properties:
              list:
                type: array
                description: "list of available triggers"
                items:
                  $ref: "../shared/schemas/Trigger.yml#/Trigger"

  createTrigger:
    200:
      description: "Trigger created"
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
                example: trigger_id
              message:
                type: string
                example: trigger created
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"

  check:
    200:
      description: "Validation is done, see response body for validation result"
      content:
        application/json:
          schema:
            $ref: "../shared/schemas/Trigger.yml#/CheckResult"
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"

trigger:
  deleteTrigger:
    200:
      description: "Trigger has been deleted"
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"

  updateTrigger:
    200:
      description: "Trigger updated"
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
                example: trigger_id
              message:
                type: string
                example: trigger created
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"

  getTrigger:
    200:
      description: "Trigger data"
      content:
        application/json:
          schema:
            $ref: "../shared/schemas/Trigger.yml#/Trigger"
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"
    404:
      $ref: "../shared/responses/_index.yml#/NotFound"

pageTriggers:
  200:
    description: "fetched matching triggers"
    content:
      application/json:
        schema:
          type: object
          properties:
            page:
              type: number
              description: "current item page"
              example: 0
            size:
              type: number
              description: "number of triggers shown per page"
              example: 10
            total:
              type: number
              description: "total number of matching results"
              example: 5
            list:
              type: array
              description: "list of matching triggers"
              items:
                $ref: "../shared/schemas/Trigger.yml#/Trigger"

searchTriggers:
  200:
    description: "fetched matching triggers"
    content:
      application/json:
        schema:
          type: object
          properties:
            page:
              type: number
              description: "current item page"
              example: 0
            size:
              type: number
              description: "number of triggers shown per page"
              example: 10
            total:
              type: number
              description: "total number of matching results"
              example: 5
            list:
              type: array
              description: "list of matching triggers"
              items:
                $ref: "../shared/schemas/Trigger.yml#/Trigger"
metrics:
  deleteMetrics:
    200:
      description: "Trigger metric has been deleted"
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"

  getMetrics:
    200:
      description: "Metrics for trigger"
      content:
        application/json:
          schema:
            type: object
            additionalProperties:
              type: array
              items:
                $ref: "../shared/schemas/MetricValue.yml#/MetricValue"
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"
    500:
      $ref: "../shared/responses/_index.yml#/ServerError"

metricsNoData:
  delete:
    200:
      description: "NODATA metrics have been deleted"
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"

render:
  getTriggerChart:
    200:
      description: "Plot for trigger"
      content:
        image/png:
          schema:
            type: string
            format: binary
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"
    404:
      $ref: "../shared/responses/_index.yml#/NotFound"
    500:
      $ref: "../shared/responses/_index.yml#/ServerError"

state:
  getTriggerState:
    200:
      description: "trigger state fetched successfully"
      content:
        application/json:
          schema:
            $ref: "../shared/schemas/TriggerCheck.yml#/TriggerCheck"
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"

setMaintenance:
  scheduleMaintenance:
    200:
      description: "trigger or metric have been scheduled for maintenance"
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"

throttling:
  getThrottleInfo:
    200:
      description: "trigger throttle info retrieved"
      content:
        application/json:
          schema:
            type: object
            properties:
              throttling:
                type: integer
                description: "unix timestamp to show next allowed time, defaults to 0"
                example: 0
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"
    404:
      $ref: "../shared/responses/_index.yml#/NotFound"

  deleteThrottleInfo:
    200:
      description: "trigger throttling has been deleted"
    404:
      $ref: "../shared/responses/_index.yml#/NotFound"
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"
