openapi: 3.0.0
info:
  description: "This is an API description for Moira Alert project. Please check https://github.com/moira-alert"
  version: "2.5.1.47"
  title: "Moira Alert"
  license:
    name: "MIT"
tags:
  - name: "config"
    description: "Runtime configuration of the API"
  - name: "triggers"
    description: "Triggers Collection Methods"
  - name: "trigger"
    description: "One Trigger Methods"

servers:
  - url: http://localhost:8080/api
    description: Localhost server
paths:
  /config:
    $ref: ./config/methods.yml
  /contact:
    $ref: ./contact/methods.yml#/contacts
  /contact/{contactId}:
    $ref: ./contact/methods.yml#/contact
  /contact/{contactId}/test:
    $ref: ./contact/methods.yml#/testContact
  /event/all:
    $ref: ./event/methods.yml#/allEvents
  /event/{triggerId}:
    $ref: ./event/methods.yml#/eventForTrigger
  /health/notifier:
    $ref: ./health/methods.yml#/notifier
  /trigger:
    $ref: ./triggers/methods.yml
  /trigger/{triggerID}:
    $ref: ./trigger/methods.yml#/trigger
  /trigger/{triggerID}/render:
    $ref: ./trigger/methods.yml#/render
  /trigger/{triggerID}/metrics:
    $ref: ./trigger/methods.yml#/metrics
  /user:
    $ref: ./user/methods.yml#/user
  /user/settings:
    $ref: ./user/methods.yml#/settings
components:
  schemas:
    $ref: "./schemas/_index.yml"
  parameters:
    $ref: "./parameters/_index.yml"
  responses:
    $ref: "./responses/_index.yml"
