name: Validate OpenAPI spec on new PR

on:
  pull_request:
    branches:
      - master

jobs:
  mergespec:
    name: Bundle spec files and validate it.
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: openapi

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - run: npm install --location=global swagger-cli @openapitools/openapi-generator-cli
      - run: make spec
      - run: make validate-spec

      - name: Save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: specfile
          path: openapi/build/openapi.yml
